script:
    - lsb_release -c -s
    - curl -s http://download.tarantool.org/tarantool/1.7/gpgkey | sudo apt-key add -
    - sudo apt-get -qq install apt-transport-https
    - echo deb https://packagecloud.io/tarantool/1_7/`lsb_release -i -s|perl -p -e 's/.*/lc $&/ge'`/ `lsb_release -c -s` main|sudo tee /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get -qq update
    - sudo apt-get -qq install tarantool
    - tarantool --version
    - prove -r t
