FROM tarantool/tarantool:@@VERSION@@
WORKDIR /opt/megaqueue
COPY start-mq.lua /opt/megaqueue
RUN luarocks --to /opt/.rocks --local install megaqueue
RUN ln -s /opt/.rocks/share/lua/5.1/ /opt/.rocks/share/tarantool
CMD [ "tarantool", "/opt/megaqueue/start-mq.lua" ]
